### ISSUE TITLE
Implement release/deployment workflow

### ISSUE THREAD

**Issue by McNetic** [validator/maven-plugin#1]
As discussed here https://github.com/validator/validator/issues/1024, there has to be a way to release and deploy the plugin to maven central.
For the release process, I usually use a ci-friendly approach (https://maven.apache.org/maven-ci-friendly.html). I'm not sure how it should be done here.

**Comment by sideshowbarker** [comment]
So shall we go ahead and bump the version number to 1.0.0 and tag and release that to the Central Repo?

**Comment by McNetic** [comment]
We probably might as well. I think we won't get any other feedback really soon.

**Comment by McNetic** [comment]
I would then like to add some information to https://validator.github.io/validator/ (there probably should be some info about the library release on maven central as well, took me some time to find it exists), but I don't see where the source is so I could provide a pull request...

**Comment by sideshowbarker** [comment]
> I would then like to add some information to https://validator.github.io/validator/ (there probably should be some info about the library release on maven central as well, took me some time to find it exists), but I don't see where the source is so I could provide a pull request...

The source for that is https://github.com/validator/validator/blob/master/index.html

**Comment by McNetic** [comment]
Would you then please release the current revision as 1.0.0?

**Comment by sideshowbarker** [comment]
> Would you then please release the current revision as 1.0.0?

Yes — sorry for the delay in getting back to this; I’ll try to get it done today

**Comment by sideshowbarker** [comment]
OK, I tagged and released version 1.0.0 — and it’s now available from the Central Repository
